name: Frontend Automated Tests CI

on: [push, pull_request]

jobs:
  frontend-test:
    name: Frontend Testing

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Run Tests
      run: npm run test

    - name: Run Build
      run: npm run build --if-present