name: ESLint Frontend CI

# The pipelie will run on every push or pull request to the main branch
on: [push, pull_request]

jobs:
  frontend-lint:
    name: Frontend Linting
    runs-on: ubuntu-latest

    # Since the project has a frontend folder, we set it as the working directory
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: ['20.x', '22.x', '24.x']

    steps:
    # 1. Checkout the code to the GitHub runner
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setup the Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }} # Specify the Node.js version you are using

    # 3. Install dependencies (Express, Jest, etc.)
    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    # 4. Run Linting
    - name: Run Lint
      run: npm run lint 

    
